//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_assignment1_console.wcfAssignment1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfAssignment1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/primeNumber", ReplyAction="http://tempuri.org/IService1/primeNumberResponse")]
        string primeNumber(int primeNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/primeNumber", ReplyAction="http://tempuri.org/IService1/primeNumberResponse")]
        System.Threading.Tasks.Task<string> primeNumberAsync(int primeNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sumOfDigits", ReplyAction="http://tempuri.org/IService1/sumOfDigitsResponse")]
        string sumOfDigits(int sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sumOfDigits", ReplyAction="http://tempuri.org/IService1/sumOfDigitsResponse")]
        System.Threading.Tasks.Task<string> sumOfDigitsAsync(int sum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reverseString", ReplyAction="http://tempuri.org/IService1/reverseStringResponse")]
        string reverseString(string reverse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reverseString", ReplyAction="http://tempuri.org/IService1/reverseStringResponse")]
        System.Threading.Tasks.Task<string> reverseStringAsync(string reverse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sortNumber", ReplyAction="http://tempuri.org/IService1/sortNumberResponse")]
        int sortNumber(int sortNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sortNumber", ReplyAction="http://tempuri.org/IService1/sortNumberResponse")]
        System.Threading.Tasks.Task<int> sortNumberAsync(int sortNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : wcf_assignment1_console.wcfAssignment1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<wcf_assignment1_console.wcfAssignment1.IService1>, wcf_assignment1_console.wcfAssignment1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string primeNumber(int primeNum) {
            return base.Channel.primeNumber(primeNum);
        }
        
        public System.Threading.Tasks.Task<string> primeNumberAsync(int primeNum) {
            return base.Channel.primeNumberAsync(primeNum);
        }
        
        public string sumOfDigits(int sum) {
            return base.Channel.sumOfDigits(sum);
        }
        
        public System.Threading.Tasks.Task<string> sumOfDigitsAsync(int sum) {
            return base.Channel.sumOfDigitsAsync(sum);
        }
        
        public string reverseString(string reverse) {
            return base.Channel.reverseString(reverse);
        }
        
        public System.Threading.Tasks.Task<string> reverseStringAsync(string reverse) {
            return base.Channel.reverseStringAsync(reverse);
        }
        
        public int sortNumber(int sortNum) {
            return base.Channel.sortNumber(sortNum);
        }
        
        public System.Threading.Tasks.Task<int> sortNumberAsync(int sortNum) {
            return base.Channel.sortNumberAsync(sortNum);
        }
    }
}
